-- Current sql file was generated after introspecting the database
-- If you want to run this migration please uncomment this code before executing migrations
/*
CREATE TABLE "users" (
	"dcid" text PRIMARY KEY NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"is_private" boolean DEFAULT false NOT NULL,
	"notify_attendance" boolean NOT NULL,
	"enable_attendance" boolean DEFAULT true NOT NULL
);
--> statement-breakpoint
CREATE TABLE "skport" (
	"dcid" text PRIMARY KEY NOT NULL,
	"user_id" text NOT NULL,
	"cred" text NOT NULL,
	"token" text NOT NULL,
	"server_id" text NOT NULL,
	"role_id" text NOT NULL,
	CONSTRAINT "cred_dcid_key" UNIQUE("dcid")
);
--> statement-breakpoint
CREATE TABLE "events" (
	"dcid" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"interaction" text NOT NULL,
	"metadata" jsonb,
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "events_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1)
);
--> statement-breakpoint
ALTER TABLE "skport" ADD CONSTRAINT "cred_dcid_fkey" FOREIGN KEY ("dcid") REFERENCES "public"."users"("dcid") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "events" ADD CONSTRAINT "events_dcid_fkey" FOREIGN KEY ("dcid") REFERENCES "public"."users"("dcid") ON DELETE cascade ON UPDATE cascade;
*/